{% set version = '1.2-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatialeco
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatialEco_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatialEco/spatialEco_{{ version }}.tar.gz
  sha256: d1ae38089228076a19fc330120f4468a6051891ac46fd604c3583a8811fe1384

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-envstats
    - r-mass
    - r-rann
    - r-rcurl
    - r-sdmtools
    - r-spatialpack >=0.3
    - r-cluster
    - r-maptools
    - r-raster
    - r-readr
    - r-rgeos
    - r-rms
    - r-sf
    - r-sp
    - r-spatstat
    - r-spdep
    - r-yaimpute
  run:
    - r-base
    - r-envstats
    - r-mass
    - r-rann
    - r-rcurl
    - r-sdmtools
    - r-spatialpack >=0.3
    - r-cluster
    - r-maptools
    - r-raster
    - r-readr
    - r-rgeos
    - r-rms
    - r-sf
    - r-sp
    - r-spatstat
    - r-spdep
    - r-yaimpute

test:
  commands:
    - $R -e "library('spatialEco')"           # [not win]
    - "\"%R%\" -e \"library('spatialEco')\""  # [win]

about:
  home: https://github.com/jeffreyevans/spatialEco
  license: GPL-3
  summary: Utilities to support spatial data manipulation, query, sampling and modelling. Functions
    include models for species population density, download utilities for climate and
    global deforestation spatial products, spatial smoothing, multivariate separability,
    point process model for creating pseudo- absences and sub-sampling, polygon and
    point-distance landscape metrics, auto-logistic model, sampling models, cluster
    optimization, statistical exploratory tools and raster-based metrics.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: spatialEco
# Type: Package
# Title: Spatial Analysis and Modelling Utilities
# Version: 1.2-0
# Date: 2019-07-23
# Authors@R: c(person(family="Evans", given="Jeffrey S.", email = "jeffrey_evans@tnc.org", role = c("aut", "cre")), person(family="Ram", given="Karthik", role = "ctb") )
# Description: Utilities to support spatial data manipulation, query, sampling and modelling. Functions include models for species population density, download utilities for climate and global deforestation spatial products, spatial smoothing, multivariate separability, point process model for creating pseudo- absences and sub-sampling, polygon and point-distance landscape metrics, auto-logistic model, sampling models, cluster optimization, statistical exploratory tools and raster-based metrics.
# Depends: R (>= 3.4.0)
# Imports: sp, sf, raster, spatstat, cluster, spdep, SDMTools, readr, RCurl, rgeos, RANN, rms, yaImpute, SpatialPack (>= 0.3), MASS, EnvStats, maptools, methods
# Maintainer: Jeffrey S. Evans <jeffrey_evans@tnc.org>
# License: GPL-3
# URL: https://github.com/jeffreyevans/spatialEco
# NeedsCompilation: no
# Repository: CRAN
# LazyData: true
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# Packaged: 2019-07-23 23:09:27 UTC; jeffrey_evans
# Author: Jeffrey S. Evans [aut, cre], Karthik Ram [ctb]
# Date/Publication: 2019-07-24 05:20:02 UTC
