travis:
  secure:
    BINSTAR_TOKEN: RDCKCNKVQdNLHzVKw9gv+mJcSLPNgOIziw8yuS7/HpnoG+QXOT9Ra57M8r1MA93a2qCUCGaj/Vafv0fPz3XzLJQtfwH1D6bhWmo/gDYBSgt1OS3/twSEq0q5OFmNObCjrugh4pnfIlgOOkxiXLUe9FjmpI9lf1kv/sH/z34ukpLKDYqdgsLr6etRIUN10LQRQhXf6t7aVAQTuh5HbcnHKs5cziYceo7xekagHPIBEQJrme9Hrw+0UBMHeABQ8NhFblN+8Zxueh/FG5mYz1jNt4AZbut/4UaigxybjvPOH1xG29A/SO2/pASVO637oazDm69wt0HZX7R8MGv+ZHa33VEUfREgVt7MP7WYluJ9LkcdJsspe5DdE+qJZWhth0UeMVGcIRYo+K67r2lyBn8eic3zeoo/JfrRXfCK8yRlLhQ9aZiAqJOdiLrQHYGhPj7eic1QudOmTs8huc5xS4xj8sNkdc+cN7dFI/2yk2QUQxlvpTK9aW/DBtPWWgUchgL0/Amhg/KjG0qXYDIoLsLGUOSZcOFUyAYZy8bsCFF1iT9HJonUsKy+yG4uhvGpN/f3CMNv3DlZ0VO4Sf9sXvG/XU4+r7dm2JeYR9odwv5Q3P/80ANBCpf1ntkE863Z+yhlb4z3cnefO9/kUiB5+CWl2pQU7WtujoBMANBrl8iJYJY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
