appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qY8lSrnHukQVBDp11HDDEleyUWL7znBApgme3YsX2tpls6O66jCz7FWakrEUMKRaUL4Mp3sNZZaytBTxfVj1WSTZeii4sjXKklfx6Rb0OMsgn18KZzXuGGs0fRZA6HxvR7F3bBiUsEaftzfdARkg+vr+Lrg/UEuWE7Z97YCkiWYyi3YN8Nd7XpCYSHseHGVUklLtHKAAXIPNr1daU93SbyUTu/CEjfDDHN4VxUaSDVMnwyAwNGxZVdAQREQDO8NXbWdTtUeXUGH1jJysfRtxp86i2L3RQZ3VoS77R7zxf9uJKkTSsA3QAnSGc80Nv7wmMT0rTltsDOy9nK6U+x4JG0HzMI4HV6n24JjHhF0qjTcYC7E7Z7AcT19tuEIXRKCy/LO8H5J0Cos7WIeqqi2iM23N0bbjX342/8kCDGOaD5NkrOYUcFRdak58zCg6AjPND0fODtRHwaJEjesOp/5sUNbPG1SllKur6ToJj0NkrBRHeiwMXQWVFTB7dgV8/C8YriNirORIF1AP22yaS8XVThdK21H/gUhtMQHD0PeHsE/pl+XB9QOqjg2XRPKkMSXCqYhRWeQPchZPjNGr+RGCSpUlYa4YaAtJ6vNVtZtbMmlo+qUU/2OIoWyy4jiKBWx4ubUOfkfhxUMUS30BLh1uGeRBmlOh2YjQavYnhzz3x3M=}
bot:
  automerge: true
